version: '2'
services:
  apache:
    image: rafaelcgstz/magento2
    # build: .
    ports:
      - "80:80" # web
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./html:/var/www/html
      - ./AddressFinder:/var/www/html/app/code/AddressFinder
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - addressfinder-magento-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - addressfinder-magento-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - addressfinder-magento-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - addressfinder-magento-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - addressfinder-magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - addressfinder-magento-network

networks:
  addressfinder-magento-network:
    driver: bridge

volumes:
  dbdata:
    driver: local